### ISSUE TITLE
Streaming Response Option in _put in `BaseRequests` library

### ISSUE THREAD

**Issue by akapur99** [mojaloop/sdk-standard-components#87]
Why should `PUT` requests have the option of a streaming response? 
in `src/lib/requests/baseRequests.js` the `_put` request has the option to allow request response to be a `Stream` which seems unusual. 
@lewisdaly and I are considering removing that option. Would appreciate any thoughts on this or if someone is currently using that feature to mention it. 
https://github.com/mojaloop/sdk-standard-components/blob/5e206644db85bc3a5b5447d7f790bfb4d04e40f4/src/lib/requests/baseRequests.js#L158

**Comment by lewisdaly** [comment]
@akapur99 please add a link to the line in question

**Comment by lewisdaly** [comment]
Closing as outdated
